### ISSUE TITLE
Better include/exclude usage

### ISSUE THREAD

**Issue by tklarryonline** [EastAgile/robber.py#11]
## Current status

Robber is checking inclusion/exclusion like this:

``` py
# Inclusion
expect([1,2,3]).to.contain(2)
expect({'foo': 'bar'}).to.contain('foo')

# Exclusion
expect([1,2,3]).to.not_contain(4)
expect({'foo': 'bar'}).to.exclude('baz')
```

Therefore, when we need to check for many members at once, we have to do this:

``` py
# Inclusion
expect([1,2,3]).to.contain(1)
expect([1,2,3]).to.contain(2)
expect([1,2,3]).to.contain(3)

# Exclusion
expect([1,2,3]).to.not_contain(4)
expect([1,2,3]).to.not_contain(5)
expect([1,2,3]).to.exclude(6)
```

Doing like this is too long!
## Change suggestions

Let's make it more verbal like:

``` py
# Inclusion
expect([1,2,3]).to.contain(1, 2, 3)

# Exclusion
expect([1,2,3]).to.not_contain(4, 5, 6)
```

**Comment by catriuspham** [comment]
@hieueastagile this sounds cool. Should we implement it?

**Comment by catriuspham** [comment]
@oyster As PR https://github.com/EastAgile/robber.py/issues/46 was merged, please help close this issue, thanks :)
