### ISSUE TITLE
String compare to unicode

### ISSUE THREAD

**Issue by hieueastagile** [EastAgile/robber.py#12]
Same as: https://github.com/vesln/robber.py/issues/9, also an issue which is described in [pandoodle-scrapy](https://github.com/EastAgile/pandoodle-dolo-scrapy/pull/5/files/5d98075c20a05c76663af472de4c325c5a437dbb#r85063309)

**Comment by catriuspham** [comment]
I couldn't reproduce this issue. I tried:

```python
expect(u'Một con mèo').to.eq('Một con mèo')
expect(u'Cat').to.eq('Cat')
```
Both passed.

**Comment by hieueastagile** [comment]
It's not the matter of comparing unicode, but the unicode inside a hash/list, please check two links that I included above @catriuspham

**Comment by catriuspham** [comment]
Ah, I just found out that this issue only occurs in Python 2.

**Comment by catriuspham** [comment]
@hieueastagile Do you want to deal with multi-level list/dict with unicode string too?
For example, this should pass:
```python
s_list = [
	['Mèo']
]
u_list = [
	[u'Mèo']
]
expect(s_list).to.eq(u_list)
```
