### ISSUE TITLE
Negate the matcher

### ISSUE THREAD

**Issue by hieueastagile** [EastAgile/robber.py#13]
Issue
====
In another language (JS), we might have this kind of syntax to negate the matcher:
```javascript
expect(something).not.to.match(something)
```
Unfortunately, in python, `not` is a keyword, it means that we can't use `not` to negate the matcher. So, we might need to find a way to do it in python as well

Some suggestions
=====
 In some libraries that I have taken a look, they tricked it by something like:
```python
expect(something).NOT.to.match(something)
```
And here what I'm thinking:
```python
expect_not(something).to.match(something)
```
Or this (seems good enough to me, IIRC, Ruby use this?)
```python
expect(something).not_to.match(something)
expect(something).have_not.match(something)
```

**Comment by hieueastagile** [comment]
@tklarryonline @nhanbt @hotay @steadykhoi Any better idea?

**Comment by tklarryonline** [comment]
`to_not` and `not_to` are actually grammatically correct, yet `not_to` is more common ([source](http://english.stackexchange.com/questions/23152/order-of-not-with-infinitive))

So, I think it's okay to provide these syntaxes:

``` py
expect(something).to_not.match(other)
expect(something).not_to.match(other)
```

`not_to` is easier to detect while skimming:

``` py
expect(something).to.match(other)
expect(others).to.match(other)
expect(something).to.match(other)
expect(something).to.match(other)
expect(others).to.match(other)
expect(something).not_to.match(other)
expect(others).to.match(other)
expect(something).to.match(other)
expect(others).to.match(other)
expect(others).to.match(other)
```

Hence my vote for `expect().not_to`.

**Comment by hieueastagile** [comment]
@tklarryonline @nhanbt @hotay @steadykhoi I'm thinking if we should support the double negated matchers? Something like `expect(something).not_to.not_to.match(abcxyz)`, or simply raise an exception in this case?

**Comment by tklarryonline** [comment]
Let's make it simple by raising an exception. Unless you want to introduce an easter egg. Something like Exploding Kittens' Nope card 😆

**Comment by tklarryonline** [comment]
On second thought, one vote for supporting multiple negated matchers. And **not** document it down. Something like this would be fun:

``` py
expect(something).not_to.not_to.not_to.not_to.not_to.not_to.not_to.not_to.not_to.match(other)
```

**Comment by hieueastagile** [comment]
Ok, I think it's better to keep it without any documentation. It's fun then.

**Comment by steadykhoi** [comment]
vote for
```python
expect(something).to.NOT.match(something)
```

**Comment by steadykhoi** [comment]
@tklarryonline IMO `not to` is not used like `expect something not to match something`. It could be right but I rarely see this tbh. The source that you cited is more commonly seen of course.

**Comment by tklarryonline** [comment]
@steadykhoi A quick search on Google Ngram Viewer shows that `expect * not to` is increasingly common in the recent years.

![screen shot 2016-11-22 at 10 50 23 am](https://cloud.githubusercontent.com/assets/2020169/20510319/e72a5450-b0a1-11e6-97b4-4a18c516a4c5.png)

[Reference](https://books.google.com/ngrams/graph?content=expect+*+not+to%2Cexpect+*+to+not&year_start=1800&year_end=2016&corpus=15&smoothing=3&share=&direct_url=t2%3B%2Cexpect%20%2A%20not%20to%3B%2Cc0%3B%2Cs0%3B%3Bexpect%20me%20not%20to%3B%2Cc0%3B%3Bexpect%20them%20not%20to%3B%2Cc0%3B%3Bexpect%20him%20not%20to%3B%2Cc0%3B%3Bexpect%20you%20not%20to%3B%2Cc0%3B%3Bexpect%20it%20not%20to%3B%2Cc0%3B%3Bexpect%20her%20not%20to%3B%2Cc0%3B%3Bexpect%20us%20not%20to%3B%2Cc0%3B%3Bexpect%20people%20not%20to%3B%2Cc0%3B%3Bexpect%20others%20not%20to%3B%2Cc0%3B%3Bexpect%20is%20not%20to%3B%2Cc0%3B.t2%3B%2Cexpect%20%2A%20to%20not%3B%2Cc0%3B%2Cs0%3B%3Bexpect%20them%20to%20not%3B%2Cc0%3B%3Bexpect%20me%20to%20not%3B%2Cc0%3B%3Bexpect%20you%20to%20not%3B%2Cc0)

**Comment by hieueastagile** [comment]
@tklarryonline @steadykhoi If you guys have some free time, please take a look on this again and let me know if there's any further discussion. If there's nothing more, I will continue with `not_to`, I prefer this more since it was used in `rspec` as well.

**Comment by steadykhoi** [comment]
Doesn't look nice to a non-rail guy like me but it's good enough.

**Comment by tklarryonline** [comment]
@hieueastagile You can support both ways if you want 😄

**Comment by hieueastagile** [comment]
@tklarryonline: One obvious way is good enough, I think we will stick with `not_to` for now.

**Comment by tklarryonline** [comment]
Good to me, then ;)

**Comment by catriuspham** [comment]
Negative matchers are implemented in https://github.com/EastAgile/robber.py/pull/15

**Comment by oyster** [comment]
Should I close this one too, @catriuspham?

**Comment by catriuspham** [comment]
@oyster Please wait until https://github.com/EastAgile/robber.py/pull/15 is merged.

**Comment by oyster** [comment]
Yeah, I saw that pull request. Let me know when I should merge and close those. Thanks.

**Comment by catriuspham** [comment]
@oyster As PR #15 is close, please help close this issue. Thanks.
