### ISSUE TITLE
Shouldn't need to call matcher() when there is no argument for it

### ISSUE THREAD

**Issue by tklarryonline** [EastAgile/robber.py#17]
## Description

I don't feel like doing this:

```py
expect(something).to.be.true()
expect(something).to.be.falsy()
expect(something).to.be.empty()
```

The function call `()` is purely redundant.

## Proposed solution

Let's remove the need to call the function. Make it beautiful like this:

```py
expect(something).to.be.true
expect(something).to.be.falsy
expect(something).to.be.empty
```

**Comment by squallcs12** [comment]
```python
expect(something).to.be.true
```
will be marked as `warning` of `statement seems to have no effect` in pycharm

**Comment by tklarryonline** [comment]
We could ignore that warning, no?

**Comment by hieueastagile** [comment]
Actually, it's just the pyCharm warnings and there's no harm, I think, `sure` do the same thing. So if there's no further discussion, it would be chosen to be implemented later, is it ok @tklarryonline @squallcs12?

**Comment by tklarryonline** [comment]
I'm okay with it since I'm the one who raised this issue 😛

**Comment by hieueastagile** [comment]
It's not possible since we can't make property and method to be the same name. So please help closing this issue if you are around @oyster @tklarryonline
