### ISSUE TITLE
to.be.called() and to.be.called

### ISSUE THREAD

**Issue by hotay** [EastAgile/robber.py#22]
Should we add these assertions?

**Comment by tklarryonline** [comment]
I think it's better to have a `robber_mock.py` plugin implemented.

**Comment by hieueastagile** [comment]
I'm still thinking about `mock`, it quite big to the scope of robber.py. If I have time, I prefer to put the effort in `robber-django` (or `robber-selenium`) than `robber-mock`.

**Comment by hieueastagile** [comment]
We can't support both of them so let's implement this with `to.be.called()` if you are going to work with this issue @catriuspham

**Comment by catriuspham** [comment]
@hieueastagile okay, I will do this in a couple of days.

**Comment by catriuspham** [comment]
@oyster This issue was solved, please help close it, thanks anh.
