### ISSUE TITLE
Ask vesln to give us ownership over robber.py

### ISSUE THREAD

**Issue by tklarryonline** [EastAgile/robber.py#23]
Basically, vesln and taoenator are not actively maintaining this package. How about asking them to transfer ownership to us?

**Comment by hieueastagile** [comment]
@tklarryonline I emailed him for a week but no response yet :(.

**Comment by hieueastagile** [comment]
Guess that we can close this now @tklarryonline @oyster

**Comment by oyster** [comment]
Ok. Please do. Thanks.

**Comment by hieueastagile** [comment]
@oyster I don't have enough permission to close it 😢
