### ISSUE TITLE
robber.py doesn't work in python 3.6

### ISSUE THREAD

**Issue by hieueastagile** [EastAgile/robber.py#24]

**Comment by catriuspham** [comment]
@hieueastagile I have just installed Python 3.6 and run robber's tests and try some simple test cases. Turns out everything works as expected. What exactly are the problems here?

**Comment by hotay** [comment]
@catriuspham
IIRC, Binh Le has tried in his bookstore project but got import error.  If you want to know more information, please don't hesitate to get him on slack.

**Comment by catriuspham** [comment]
OK. slacking him :D

**Comment by catriuspham** [comment]
This was fixed in https://github.com/EastAgile/robber.py/pull/28

**Comment by catriuspham** [comment]
@oyster Please help close this issue
