### ISSUE TITLE
Enable CodeClimate for robber.py and add the badge to README

### ISSUE THREAD

**Issue by hieueastagile** [EastAgile/robber.py#35]

**Comment by catriuspham** [comment]
Only owner or admin of a repo are allowed to add it to CodeClimate. Should I ask anh Quang for help?

**Comment by hieueastagile** [comment]
@catriuspham It's open-source, we don't need any permission to add it into CodeClimate

**Comment by catriuspham** [comment]
![screenshot from 2017-05-09 15-37-25](https://cloud.githubusercontent.com/assets/17242255/25842208/71ab64f2-34cd-11e7-887d-50ec98bc915e.png)

That's weird but I cannot find it :(

**Comment by hieueastagile** [comment]
I guess you did something wrong there, anyway, just let me take a look on it later.

**Comment by hieueastagile** [comment]
You can see the result here:https://codeclimate.com/github/vesln/robber.py. Actually, there's no setup needed, we just need to add it to our profile then we can see it for any open-source project.

**Comment by catriuspham** [comment]
Oh, I was trying to add Eastagile/robber.py :sweat_smile:

**Comment by catriuspham** [comment]
@oyster Please help close this issue, thanks.

**Comment by hieueastagile** [comment]
It works the same to the EA repo, I think.
