### ISSUE TITLE
Python 2.6 shows no error messages

### ISSUE THREAD

**Issue by catriuspham** [EastAgile/robber.py#36]
For example, we have this expectation:
```python
expect(1).to.eq(2)
```
In Python 3, we get this error message:
```python
robber.bad_expectation.BadExpectation: Expected int("1") to equal int("2")
```
But in Python 2.6, we only get this:
```python
BadExpectation
```

**Comment by hieueastagile** [comment]
It could be how the base exception was string-ify, I think we can override this via `__str__` or `__repr__` somehow, not really an issue then.

**Comment by tklarryonline** [comment]
Since `__str__` is overridden already, I think we could add `__repr__` as well.
