### ISSUE TITLE
Some suggestions after investigating Sure

### ISSUE THREAD

**Issue by catriuspham** [EastAgile/robber.py#37]
So I read through Sure's docs, and realize some things we could do with our library.

- [String similarity](http://sure.readthedocs.io/en/latest/api-reference.html#look-like): this compares the similarity of 2 string. For example, `This is a string` should look alike `tHIS is A strinG`
- [.be.ok](http://sure.readthedocs.io/en/latest/api-reference.html#be-ok): exactly the same as our `.be.truthy` but sound better. 
- [.be.a(type)](http://sure.readthedocs.io/en/latest/api-reference.html#be-a-type): this is much more general than our current style (`be.a.type`) as we don't have to implement much.

**Comment by hieueastagile** [comment]
@catriuspham : Here's my opinion:
- String similarity is great, we can implement it.
- I prefer be.truthy, since we can use be.falsy and it seems more meaningful.
- I don't remember we have `be.a.type`?

And, I think the explanation system should be our priority for now.

**Comment by catriuspham** [comment]
@hieueastagile we can do this:

```python
expect(1).to.be.an.integer()
expect('a').to.be.a.string()
```

What do you mean by explanation system? Is it the same as the `DeepExplaination` thingy that you mentioned in this PR: https://github.com/EastAgile/robber.py/pull/31?
