### ISSUE TITLE
Better explaination system

### ISSUE THREAD

**Issue by catriuspham** [EastAgile/robber.py#39]
I have looked at Sure's DeepExplaination and come up with an idea for our explanation system.
All the failure message will have the following format, from which the second and the third line can be omitted. 

```python
BadExpectation:
A = ...
B = ...
C = ...
Expected A to {action} B. 
{more_detail}
```

For example: 

`expect(1).to.eq(2)`

will show us this error message:

```python
BadExpectation:
A = 1
B = 2
Expected A to equal B. 
```

Another example:
```python
mock(1, 2, a=3)
expect(mock).to.be.called_with(4, 5, b=6)
```
gives us this error message:

```
BadExpectation:
A = [represented string of mock]
B = 1, 2, a=3
C = 4, 5, b=6
Expected A to be called with B.
Actually called with C. 
```

**Comment by hieueastagile** [comment]
Sounds good to me :+1:

**Comment by catriuspham** [comment]
@oyster Please help close this issue also, thanks.
