### ISSUE TITLE
change, increase, decrease matchers

### ISSUE THREAD

**Issue by hieueastagile** [EastAgile/robber.py#5]
# Use case

Example, we have a function

``` python
def decrease_it(a):
  return a - 1
```

We might want to test it, and here's a few possible matchers that we might want to use

``` python
expect(decrease_it).to.change(a).from(2).to(1)
expect(decrease_it).to.decrease(a).by(1)
expect(decrease_it).to.increase(a).by(-1)
```

**Comment by hieueastagile** [comment]
We might need to resolve this first: https://github.com/EastAgile/robber.py/issues/4

**Comment by catriuspham** [comment]
I see that we aldready have the chain `expect(func).to.change(arg).by(arg)`. Do we still need these `change.from.to`, `decrease`, `increase` chains?

**Comment by hieueastagile** [comment]
from... to doesn't work, actually, since `from` is python keywords, that's why @hotay use change... by instead.

**Comment by catriuspham** [comment]
How about decrease and increase then? Do we still need to implement them?

**Comment by hieueastagile** [comment]
We should do.

**Comment by catriuspham** [comment]
@hieueastagile our current `change.by` is the same as your suggested `increase.by` do you want to keep both or just one of them?

**Comment by hieueastagile** [comment]
@catriuspham Looking into it again. I think we should close this issue, change.by is good enough and it should be the only obvious way for this, we don't need to introduce more ways, it seems to break the Python Zen here.
