### ISSUE TITLE
Chain matcher's unexpected behaviors

### ISSUE THREAD

**Issue by catriuspham** [EastAgile/robber.py#51]
Running this `expect(expect).to.have.chain('to')` in ipython returns `AttributeError`. But running the same code with nosetests still passes.

**Comment by hieueastagile** [comment]
Can you give me a full piece of code @catriuspham?

**Comment by catriuspham** [comment]
@hieueastagile I found out the problem. `nosetests` automatically runs through the `test/__init__.py` which imports the `chain_matcher`.

**Comment by hieueastagile** [comment]
I don't really get it, could you give more code and explanation?

**Comment by catriuspham** [comment]
You can see that in `tests/test_expect.py` we have a lot of tests that use chain matcher. And all tests pass when running `nosetests`. Then I use ipython and run the exact same code from the line 29 in  `tests/test_expect.py` which is `expect(expect).to.have.chain('to')`, and it raises `AttributeError: 'expect' object has no attribute 'chain'`.

**Comment by catriuspham** [comment]
So I think this behavior is expected, the chain matcher is only available for testing purpose. It's a feature, not a bug :laughing:
