### ISSUE TITLE
Make TravisCI and Coverage report correctly for codes that support multiple Python version

### ISSUE THREAD

**Issue by catriuspham** [EastAgile/robber.py#59]
For example, I have this pseudo code:
```
If Python2:
    do_something
else if Python3:
    do_something_else
```
I can write a test for it, easily. But the test runner can never cover all the lines because it can only run on one python version at a time.

**Comment by hieueastagile** [comment]
It's not a big deal, let the coverage ignore these lines. Anyway, I think we should do less the approach `if python2 else if python3` if possible.

**Comment by catriuspham** [comment]
Yeah, in some cases we have to. For example, that `OrderDict` as it's only supported in Python >= 2.7. I used a `try except` to deal with it, but it met the same trouble with coverage though.
