### ISSUE TITLE
Match exception by string/regex

### ISSUE THREAD

**Issue by hieueastagile** [EastAgile/robber.py#8]
Currently, we only have exception to be matched by the object, but there's use cases that we want to match it by string or regex, something like

``` python
expect(any_callable).to.throw('DivisionByZero')
# with regex
expect(any_callable).to.throw('Division(.)+')
```

**Comment by catriuspham** [comment]
Do you want to handle these cases inside the current `throw` chain or create a new chain for it?

```python
expect(any_callable).to.throw_exception_named('Division(.)+')
```

**Comment by hieueastagile** [comment]
If we do it, I guess we should put it into the current `throw` chain.

Anyway, I proposed this story before because `sure` had the same functionality. But I'm not very sure that there's a use-case that we need this, wdyt @catriuspham?

**Comment by catriuspham** [comment]
I find using `string` to indicate an exception class is rather awkward. In an edge case that @nhanbt suggested, if we have 2 custom exception classes with the same name in the code base, then things will be really ambiguous. To me, I think we'd better keep the current logic as is.

**Comment by hieueastagile** [comment]
Ok, so it's better not to implement this. Close this now, thanks @catriuspham
