### ISSUE TITLE
Match exception exactly

### ISSUE THREAD

**Issue by hieueastagile** [EastAgile/robber.py#9]
Meanwhile, we are checking exception by using `isinstance` function, that means if we have ParentException and ChildExcetion, then if `callable` trigger ChildException, then

``` python
expect(callable).to.throw(ParentException) 
```

would be ok too.

In some case, we might want to check exactly the exception which was raised, so, we might want

``` python
expect(callable).to.throw.exactly(ChildException)
```

**Comment by hieueastagile** [comment]
We might need to resolve this first: https://github.com/EastAgile/robber.py/issues/4

**Comment by catriuspham** [comment]
@oyster Please close this issue too, thanks.
